//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTS.Jurnal.Database.SQLServer.Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filter
    {
        public Filter()
        {
            this.FilterItems = new HashSet<FilterItem>();
        }
    
        public int Id { get; set; }
        public bool IsActive { get; set; }
        public int FilterGroup_Id { get; set; }
        public int FilterType_Id { get; set; }
    
        public virtual FilterGroup FilterGroup { get; set; }
        public virtual FilterType FilterType { get; set; }
        public virtual ICollection<FilterItem> FilterItems { get; set; }
    }
}
