//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTS.Jurnal.Database.SQLServer.Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilterGroup
    {
        public FilterGroup()
        {
            this.Filters = new HashSet<Filter>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsIntervalActive { get; set; }
    
        public virtual ICollection<Filter> Filters { get; set; }
    }
}
