//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTS.Jurnal.Database.SQLServer.Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intervention
    {
        public int Id { get; set; }
        public string Observation { get; set; }
        public int Number { get; set; }
        public double Revenue { get; set; }
        public double Percent { get; set; }
        public int Patient_id { get; set; }
        public Nullable<int> Location_Id { get; set; }
        public Nullable<int> Material_Id { get; set; }
        public int DateHourDetail_Id { get; set; }
        public Nullable<int> Area_Id { get; set; }
        public Nullable<int> Work_Id { get; set; }
        public int Year_Id { get; set; }
        public int Month_Id { get; set; }
        public Nullable<bool> WasPayedByDental { get; set; }
        public Nullable<int> TechnicianId { get; set; }
        public Nullable<double> MaterialCost { get; set; }
        public bool IsSelected { get; set; }
        public double Remainder { get; set; }
        public int UserId { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual DateHourDetail DateHourDetail { get; set; }
        public virtual Location Location { get; set; }
        public virtual Work Work { get; set; }
        public virtual Material Material { get; set; }
        public virtual Month Month { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Technician Technician { get; set; }
        public virtual Year Year { get; set; }
    }
}
