//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTS.Jurnal.Database.SQLServer.Module
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dsaEntities : DbContext
    {
        public dsaEntities()
            : base("name=dsaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Area> Areas { get; set; }
        public DbSet<DateHourDetail> DateHourDetails { get; set; }
        public DbSet<DentalPaymentInfo> DentalPaymentInfoes { get; set; }
        public DbSet<FilterGroup> FilterGroups { get; set; }
        public DbSet<FilterItem> FilterItems { get; set; }
        public DbSet<Filter> Filters { get; set; }
        public DbSet<FilterType> FilterTypes { get; set; }
        public DbSet<IntervalInfo> IntervalInfoes { get; set; }
        public DbSet<Intervention> Interventions { get; set; }
        public DbSet<Location> Locations { get; set; }
        public DbSet<MAC> MACs { get; set; }
        public DbSet<Material> Materials { get; set; }
        public DbSet<Month> Months { get; set; }
        public DbSet<Patient> Patients { get; set; }
        public DbSet<ProgramInfo> ProgramInfoes { get; set; }
        public DbSet<Technician> Technicians { get; set; }
        public DbSet<Type> Types { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Work> Works { get; set; }
        public DbSet<WorkType> WorkTypes { get; set; }
        public DbSet<Year> Years { get; set; }
    }
}
