//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTS.Jurnal.Database.SQLServer.Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.Interventions = new HashSet<Intervention>();
            this.Types = new HashSet<Type>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public double Cost { get; set; }
        public Nullable<bool> WasDeleted { get; set; }
    
        public virtual ICollection<Intervention> Interventions { get; set; }
        public virtual ICollection<Type> Types { get; set; }
    }
}
