//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTS.Jurnal.Database.SQLServer.Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.Interventions = new HashSet<Intervention>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Street { get; set; }
        public string Block { get; set; }
        public string Job { get; set; }
        public string StreetNumber { get; set; }
        public string Ocupation { get; set; }
        public string Country { get; set; }
        public int UserId { get; set; }
    
        public virtual ICollection<Intervention> Interventions { get; set; }
        public virtual User User { get; set; }
    }
}
