//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTS.Jurnal.Database.SQLServer.Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class Year
    {
        public Year()
        {
            this.Interventions = new HashSet<Intervention>();
        }
    
        public int Id { get; set; }
        public int YearNb { get; set; }
    
        public virtual ICollection<Intervention> Interventions { get; set; }
    }
}
